name: Deploy to Firebase

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  API_SERVICE_NAME: skillex-api
  REGION: us-central1

jobs:
  # Deploy API to Cloud Run
  deploy-api:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account.json
          gcloud auth activate-service-account --key-file=/tmp/service-account.json
          gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Create Artifact Registry repository
        run: |
          gcloud artifacts repositories create skillex \
            --repository-format=docker \
            --location=$REGION \
            --description="Skillex API Docker repository" || true

      - name: Build and push Docker image
        run: |
          docker build -f apps/api/Dockerfile -t $REGION-docker.pkg.dev/$PROJECT_ID/skillex/$API_SERVICE_NAME:$GITHUB_SHA .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/skillex/$API_SERVICE_NAME:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          export ALLOWED_ORIGINS_ESCAPED="${{ secrets.ALLOWED_ORIGINS }}"
          gcloud run deploy $API_SERVICE_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/skillex/$API_SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 2 \
            --set-env-vars NODE_ENV=production \
            --set-env-vars DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            --set-env-vars SUPABASE_JWKS_URL="${{ secrets.SUPABASE_JWKS_URL }}" \
            --set-env-vars ALLOWED_ORIGINS="$ALLOWED_ORIGINS_ESCAPED" \
            --set-env-vars RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}"
            

          
  # Deploy Web App to Cloud Run
  deploy-web:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/service-account.json
          gcloud auth activate-service-account --key-file=/tmp/service-account.json
          gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Create Artifact Registry repository for web
        run: |
          gcloud artifacts repositories create skillex-web \
            --repository-format=docker \
            --location=$REGION \
            --description="Skillex Web Docker repository" || true

      - name: Build and push Docker image for web
        run: |
          docker build -f apps/web/Dockerfile -t $REGION-docker.pkg.dev/$PROJECT_ID/skillex-web/skillex-web:$GITHUB_SHA apps/web
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/skillex-web/skillex-web:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy skillex-web \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/skillex-web/skillex-web:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --port 3000 \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10 \
            --set-env-vars NEXT_PUBLIC_API_URL=https://skillex-api-$PROJECT_ID.a.run.app \
            --set-env-vars NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --set-env-vars NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            --set-env-vars NEXT_PUBLIC_PLAUSIBLE_DOMAIN=${{ secrets.NEXT_PUBLIC_PLAUSIBLE_DOMAIN }}
